---
name: Varo
version: 1.0.8
author: timmyRS
website: https://github.com/timmyrs/Varo

main: de.timmyrs.Varo

commands:
  team:
    usage: /team [[info]|[invite ]<player>|help|requests|leave]
  t:
    usage: /t <message>
  varo:
    usage: /varo [tp <player>|start|end|savedefaultitems|flush|reload]
