---
name: Varo
version: 1.2.6
main: de.timmyrs.Varo
api-version: 1.12.2
author: timmyRS
website: https://github.com/timmyrs/Varo

commands:
  team:
    usage: /team [[info]|[invite ]<player>|help|requests|leave]
  t:
    usage: /t <message>
  varo:
    usage: /varo [tp <player>|tpcenter|start|end|savedefaultitems|flush|reload]

permissions:
  varo.*:
    default: op
    description: Grants all varo.* permissions
    children:
      varo.admin: true
  varo.admin:
    description: Allows the player to use all Varo admin commands
    children:
      varo.start: true
  varo.start:
    description: Allows the player to use /varo start
